#CXXFLAGS =	-O2 -g -Wall -fmessage-length=0
export CXXFLAGS_GLOBAL

BINDIR = ../bin/

OBJSDIR = ../objs/

OBJS =		

LIBS =

TARGET = 
	
.PHONY:		all	Fenger 

all:	Fenger

Fenger:	
	(cd ./Fenger; make all)

clean:
	(cd ./Fenger; make clean)